version: "3.8"
services:
  api-gateway:
    build: ./APIGateway
    ports:
      - 7000:80
  follower-service:
    build: ./FollowerService
    ports:
      - 7010:80
  user-service:
    build: ./UserService
    ports:
      - 7020:80
  post-service:
    build: ./PostService
    ports:
      - 7030:80
  media-service:
    build: ./MediaService
    ports:
      - 7040:80